# Generated by Django 4.2.6 on 2023-10-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('classroom_number', models.IntegerField(default=3)),
                ('recording_number', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=2)),
                ('classroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recap.person')),
            ],
        ),
    ]
